name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Required for deployment to gh-pages

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Clean previous deployment files
        run: |
          rm -rf github-pages-deploy-action-temp-deployment-folder
          git worktree prune

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: |
          npm run blog
          npm run sitemap
          npm run build
          npm run export
          touch out/.nojekyll
        env:
          CI: true

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.RB }}
          branch: gh-pages
          folder: out
